language: php
php:
- 5.3
before_script: composer install --dev
script:
- bin/atoum -d tests/units
deploy:
  provider: heroku
  api_key:
    secure: BAai4eaFzRnbS2ogvObRwMUG4g0Arp/aoRloTdJsJ2FKGcchoJa9zNgoiGTsx/1T7MhD+OaEJYi5Lu5PGV2QZ+3lS6/vfQX1nd8xUp8WqTmFATTcznUjclRp/0StQbvWsA4pM+Q+O6GkSadaaC6sXD15eVnRQYlUqRB3jPnU4oA=
  app: cryptic-gorge-4817
  on:
    repo: pimpin/gestion_projet
