language: php
php:
- 5.3
before_script: composer install --dev
script:
- bin/atoum -d tests/units
deploy:
  provider: heroku
  api_key:
    secure: vfE7vF0cPgM4FEBy3IHm2+1giyuHEzMr0VE2qTB/LMmUR3OKs7I0fwbwVMo3SxPQzOA/uJnqvGSND53zRqaBmoLy1q6D+L9rYjUbxUsbGwgjqm8teK2XGskjaDOUrvbNVh38KhIUJ6dlPT6L3Gg2q6INaK1OVDuYSnFYsUOLWvw=
  app: protected-retreat-6439
  on:
    repo: pimpin/gestion_projet
